FROM  openjdk:8-jre

VOLUME /home/order
RUN mkdir -p /home/order
WORKDIR /home/order
COPY ./jar/OrdersProject-0.0.1-SNAPSHOT.jar /home/order/OrdersProject-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","OrdersProject-0.0.1-SNAPSHOT.jar"]